#define b_TOKEN 'b'
#define B_TOKEN 'B'
#define NULL_TOKEN '\0'
#define EQUAL_TOKEN '='
#define COMMA_TOKEN ','
#define COLON_TOKEN ':'
#define HYPHEN_TOKEN '-'
#define PERIOD_TOKEN '.'
#define DQUOTE_TOKEN '"'
#define COMMENT_TOKEN '!'
#define BW_SLASH_TOKEN '\\'
#define NEW_LINE_TOKEN '\n'
#define TABSPACE_TOKEN '\t'
#define WHITESPACE_TOKEN ' '
#define UNDERSCORE_TOKEN '_'
#define OPEN_PARANTH_TOKEN '('
#define CLOSE_PARANTH_TOKEN ')'

